//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебное_заведение
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsSet
    {
        public int Id { get; set; }
        public int IdLesson { get; set; }
        public int IdStudent { get; set; }
        public double Point { get; set; }
    
        public virtual LessonsSet LessonsSet { get; set; }
        public virtual StudentsSet StudentsSet { get; set; }
    }
}
